### PR TITLE
Store ID token not access token for ID token in extra info

### PR DESCRIPTION
**Pull request by ryanswood**
Followup to https://github.com/omniauth/omniauth-okta/pull/17 which replaces the access token with the ID token in the extra info.

This PR slightly changes the solution and includes a spec.

### CODE REVIEW

**Comment by rockorequin** [comment]
+1 for this. 

Btw, should it check oauth2_access_token['id_token'] is not nil as well as oauth2_access_token?

**Comment by ryanswood** [comment]
@rockorequin 

> Btw, should it check oauth2_access_token['id_token'] is not nil as well as oauth2_access_token?

I am not sure though I do prefer to leave as is. It is much more clear to have the `extra` info hash contain the key `id_token` with a nil value as a way to explain the ID's absence rather than not having the key. Plus, this code has worked this way for ~5 years so it would be problematic if the key were not to exist on the next release. 

@rockorequin Thoughts?

@BobbyMcWho What are the steps to get this merged? Let me know if there is anything else needed.

**Comment by ryanswood** [comment]
@rockorequin 

> Btw, should it check oauth2_access_token['id_token'] is not nil as well as oauth2_access_token?

I am not sure though I do prefer to leave as is. It is much more clear to have the `extra` info hash contain the key `id_token` with a nil value as a way to explain the ID's absence rather than not having the key. Plus, this code has worked this way for ~5 years so it would be problematic if the key were not to exist on the next release. 

@rockorequin Thoughts?

@BobbyMcWho What are the steps to get this merged? Let me know if there is anything else needed.

**Comment by rockorequin** [comment]
@ryanswood Good points, I agree. 

Also, fwiw I tested the patch and it works fine with my logout code.

Is it possible that someone might be using the access token (that is currently mislabeled as id_token)? In which case, would it be a good idea to at least add a note to the readme file saying that the id_token key now actually refers to the id_token instead of the access_token?

**Comment by BobbyMcWho** [comment]
Yeah, when this gets merged it'll be a major version bump most likely since it breaks the existing expected data

**Comment by ryanswood** [comment]
@BobbyMcWho PR look good? Anything else needed? I am assuming the PR would be merged and you would bump the version and do a release?

**Comment by ryanswood** [comment]
@BobbyMcWho PR look good? Anything else needed? I am assuming the PR would be merged and you would bump the version and do a release?

**Comment by BobbyMcWho** [comment]
@ryanswood @rockorequin please check out #25

**Comment by BobbyMcWho** [comment]
I appreciate your patience on this folks, this has been released in [v2.0.0](https://github.com/omniauth/omniauth-okta/releases/tag/v2.0.0). Released on [rubygems](https://rubygems.org/gems/omniauth-okta/versions/2.0.0).

**Pull request closed without merging**
